# Generated by Django 4.0.4 on 2022-05-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de la Categoría')),
                ('nombreC', models.CharField(max_length=30, verbose_name='Nombre de la Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='código del Producto')),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='Nombre del Producto')),
                ('descCorta', models.CharField(max_length=30, verbose_name='Descripción Corta del Producto')),
                ('descLarga', models.CharField(max_length=200, verbose_name='Descripción Detallada del Producto')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('stock', models.IntegerField(verbose_name='Cantidad en Stock del Producto')),
                ('foto', models.ImageField(null=True, upload_to='core')),
            ],
        ),
    ]
