# Generated by Django 4.0.4 on 2022-06-06 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la Categoría')),
                ('nombreC', models.CharField(max_length=30, verbose_name='Nombre de la Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('idEstatus', models.AutoField(primary_key=True, serialize=False, verbose_name='Código de la Categoría')),
                ('nombreE', models.CharField(max_length=30, verbose_name='Nombre del Estatus')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Código del Producto')),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='Nombre del Producto')),
                ('descCorta', models.CharField(max_length=30, verbose_name='Descripción Corta del Producto')),
                ('descLarga', models.CharField(max_length=200, verbose_name='Descripción Detallada del Producto')),
                ('precio', models.IntegerField(verbose_name='Precio del Producto')),
                ('stock', models.IntegerField(verbose_name='Cantidad en Stock del Producto')),
                ('foto', models.ImageField(default='core/default.png', null=True, upload_to='core/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('estatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estatus')),
            ],
        ),
    ]
