# Generated by Django 4.0.4 on 2022-06-22 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='idCategoria',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de la Categoría'),
        ),
        migrations.AlterField(
            model_name='estatus',
            name='idEstatus',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Código de la Categoría'),
        ),
    ]
